'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace localhost
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="MyServiceClassPortBinding", [Namespace]:="http://MyPackage/")>  _
    Partial Public Class MyServiceClassService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SayHelloOperationCompleted As System.Threading.SendOrPostCallback
        
        Private AddNumbersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SayHiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.WebserviceClient.My.MySettings.Default.WebserviceClient_localhost_MyServiceClassService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SayHelloCompleted As SayHelloCompletedEventHandler
        
        '''<remarks/>
        Public Event AddNumbersCompleted As AddNumbersCompletedEventHandler
        
        '''<remarks/>
        Public Event SayHiCompleted As SayHiCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://MyPackage/", ResponseNamespace:="http://MyPackage/", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function SayHello(ByVal arg0 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("SayHello", New Object() {arg0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SayHelloAsync(ByVal arg0 As String)
            Me.SayHelloAsync(arg0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SayHelloAsync(ByVal arg0 As String, ByVal userState As Object)
            If (Me.SayHelloOperationCompleted Is Nothing) Then
                Me.SayHelloOperationCompleted = AddressOf Me.OnSayHelloOperationCompleted
            End If
            Me.InvokeAsync("SayHello", New Object() {arg0}, Me.SayHelloOperationCompleted, userState)
        End Sub
        
        Private Sub OnSayHelloOperationCompleted(ByVal arg As Object)
            If (Not (Me.SayHelloCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SayHelloCompleted(Me, New SayHelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://MyPackage/", ResponseNamespace:="http://MyPackage/", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function AddNumbers(ByVal arg0 As Integer, ByVal arg1 As Integer) As <System.Xml.Serialization.XmlElementAttribute("return")> Integer
            Dim results() As Object = Me.Invoke("AddNumbers", New Object() {arg0, arg1})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AddNumbersAsync(ByVal arg0 As Integer, ByVal arg1 As Integer)
            Me.AddNumbersAsync(arg0, arg1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AddNumbersAsync(ByVal arg0 As Integer, ByVal arg1 As Integer, ByVal userState As Object)
            If (Me.AddNumbersOperationCompleted Is Nothing) Then
                Me.AddNumbersOperationCompleted = AddressOf Me.OnAddNumbersOperationCompleted
            End If
            Me.InvokeAsync("AddNumbers", New Object() {arg0, arg1}, Me.AddNumbersOperationCompleted, userState)
        End Sub
        
        Private Sub OnAddNumbersOperationCompleted(ByVal arg As Object)
            If (Not (Me.AddNumbersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AddNumbersCompleted(Me, New AddNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://MyPackage/", ResponseNamespace:="http://MyPackage/", Use:=System.Web.Services.Description.SoapBindingUse.Literal)>  _
        Public Function SayHi(ByVal arg0 As String) As <System.Xml.Serialization.XmlElementAttribute("return")> String
            Dim results() As Object = Me.Invoke("SayHi", New Object() {arg0})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SayHiAsync(ByVal arg0 As String)
            Me.SayHiAsync(arg0, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SayHiAsync(ByVal arg0 As String, ByVal userState As Object)
            If (Me.SayHiOperationCompleted Is Nothing) Then
                Me.SayHiOperationCompleted = AddressOf Me.OnSayHiOperationCompleted
            End If
            Me.InvokeAsync("SayHi", New Object() {arg0}, Me.SayHiOperationCompleted, userState)
        End Sub
        
        Private Sub OnSayHiOperationCompleted(ByVal arg As Object)
            If (Not (Me.SayHiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SayHiCompleted(Me, New SayHiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub SayHelloCompletedEventHandler(ByVal sender As Object, ByVal e As SayHelloCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SayHelloCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub AddNumbersCompletedEventHandler(ByVal sender As Object, ByVal e As AddNumbersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AddNumbersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub SayHiCompletedEventHandler(ByVal sender As Object, ByVal e As SayHiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SayHiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
